name: pydl

channels:
    - astropy

dependencies:
    - python>=3.6
    - astropy
    - Cython
    - matplotlib
    - numpy
    - scipy
#     - sphinx-astropy
    - pip:
        - sphinx-astropy
        - sphinx-gallery
